name: Protect Dependabot Alerts
# This workflow protects against accidental dismissal of Dependabot alerts
on:
on:
  workflow_dispatch:
    inputs:
      alert_number:
        description: "Dependabot alert number"
        required: true
        type: string
        default: "0"

permissions:
  contents: read
  security-events: write

jobs:
  call-protector:
    uses: Posture-Cybersecurity/.github/.github/workflows/protect-dependabot.yml@main
    with:
      alert_number: ${{ format('{0}', inputs.alert_number) }}
    secrets: inherit