name: Protect Dependabot Alerts
on:
  workflow_call:
    inputs:
      alert_number:
        required: true
        type: string
# 
permissions:
  contents: read
  security-events: write

jobs:
  call-protector:
    uses: Posture-Cybersecurity/.github/.github/workflows/protect-dependabot.yml@main
    with:
      alert_number: ${{ inputs.alert_number }}
    secrets: inherit