name: Protect Dependabot Alerts
# This workflow protects against accidental dismissal of Dependabot alerts
on:
  workflow_call:
    inputs:
      alert_number:
        required: true
        type: string
  repository_dispatch:
    types: [dependabot_alert_dismissed]

permissions:
  contents: read
  security-events: write

jobs:
  call-protector:
    uses: Posture-Cybersecurity/.github/.github/workflows/protect-dependabot.yml@main
    with:
      alert_number: ${{ github.event.client_payload.alert_number || inputs.alert_number }}
    secrets: inherit